version: '3.8'
services:
  db:
    image: postgres:13
    container_name: workout_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=workout_db
    ports:
      - "5432:5432"
   